from abc import ABC, abstractmethod
from typing import Any

from pydantic import BaseModel, Field


class AIResponse(BaseModel):
    """Normalized response payload across all AI providers."""

    content: str = Field(
        ..., description="The textual content generated by the AI model"
    )
    provider: str = Field(
        ..., description="The name of the provider that generated the response"
    )
    model: str | None = Field(None, description="The specific model identifier used")
    metadata: dict[str, Any] = Field(
        default_factory=dict, description="Raw metadata or usage statistics"
    )


class AIProvider(ABC):
    """
    Abstract Base Class defining the contract for AI providers.
    All vendor-specific implementations (OpenAI, Groq, HuggingFace, etc.)
    must conform strictly to this interface.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """The unique identifier name of the AI provider."""
        pass

    @abstractmethod
    def is_configured(self) -> bool:
        """Determine whether the provider has the requisite credentials configured."""
        pass

    @abstractmethod
    async def generate_text(
        self,
        prompt: str,
        system_prompt: str | None = None,
        **kwargs: Any,
    ) -> AIResponse:
        """Generate text completion from a prompt."""
        pass

    @abstractmethod
    async def chat(
        self,
        messages: list[dict[str, str]],
        **kwargs: Any,
    ) -> AIResponse:
        """Execute a conversational chat completion given a list of messages."""
        pass
